engines:
  pmd:
    enabled: true
    options:
      language: apex

  eslint:
    enabled: true
    options:
      language: javascript

rules:
  pmd:
    - apex/no-global-sosl
    - apex/no-hardcoded-ids

  eslint:
    - eslint/no-unused-vars
    - eslint/no-console
