name: Salesforce Metadata Deploy
description: Builds and deploys metadata to a specified environment
author: accadzo
branding:
  icon: code
  color: blue

inputs:
  DRY_RUN:
    description: "Validate deploy and run Apex tests but don't save to the org." 
    type: boolean
  TEST_LEVEL:
    description: "Deployment Apex testing level."
    type: choice
    default: RunLocalTests
    options:
      - NoTestRun
      - RunSpecifiedTests
      - RunLocalTests
      - RunAllTestsInOrg
  WAIT:
    description: "Number of minutes to wait for command to complete and display results."
    type: number
    default: 30
  SFDX_AUTH_URL:
    description: "The auth url tied to your deployment environment"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
    - name: Login to Environment
      shell: bash
      run: |
        sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SFDX_AUTH_URL }}")
    - name: Query Latest Deployment ID
      shell: bash
      id: get-deploy-id
      run: |
        echo "Querying the latest deployment ID..."
        QUERY_RESULT=$(sf data query --query "SELECT Id FROM DeployRequest ORDER BY CreatedDate DESC LIMIT 1" --json --use-tooling-api)
        echo "Query Result: $QUERY_RESULT"
        DEPLOY_ID=$(echo $QUERY_RESULT | jq -r '.result.records[0].Id')
        if [ -z "$DEPLOY_ID" ]; then
          echo "Error: Unable to fetch the latest deployment ID."
          exit 1
        fi
        TRUNCATED_DEPLOY_ID=${DEPLOY_ID::-3}
        echo "Quick deploy ID: $TRUNCATED_DEPLOY_ID"
        echo "QUICK_DEPLOY_ID=$TRUNCATED_DEPLOY_ID" >> $GITHUB_ENV

    - name: Quick Deploy
      shell: bash
      run: |
        echo "Performing quick deploy"
        sf project deploy quick --job-id $QUICK_DEPLOY_ID --wait 10
