name: Salesforce Metadata Deploy
description: Builds and deploys metadata to a specified environment
author: accadzo
branding:
  icon: code
  color: blue

inputs:
  DRY_RUN:
    description: "Validate deploy and run Apex tests but don't save to the org." 
    type: boolean
  TEST_LEVEL:
    description: "Deployment Apex testing level."
    type: choice
    default: RunLocalTests
    options:
      - NoTestRun
      - RunSpecifiedTests
      - RunLocalTests
      - RunAllTestsInOrg
  WAIT:
    description: "Number of minutes to wait for command to complete and display results."
    type: number
    default: 30
  SFDX_AUTH_URL:
    description: "The auth url tied to your deployment environment"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
    - name: Login to Environment
      shell: bash
      run: |
        sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SFDX_AUTH_URL }}")
    - name: Capture Deployment ID
      shell: bash
      id: get-deploy-id
      run: |
        DEPLOY_ID=$(sf project deploy report --use-most-recent --json | jq -r .result.id)
        TRUNCATED_DEPLOY_ID=${DEPLOY_ID::-3}
        echo "Quick deploy ID: $TRUNCATED_DEPLOY_ID"
        echo "QUICK_DEPLOY_ID=$TRUNCATED_DEPLOY_ID" >> $GITHUB_ENV

    - name: Quick Deploy
      shell: bash
      run: |
        echo "quick deploy"
        sf project deploy quick --job-id $QUICK_DEPLOY_ID --wait 10
