name: Deploy To Test

on:
  pull_request_review:
    branches:
      - test
    paths:
      - 'force-app/**'
    types:
      - submitted

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Approvals and Workflow Status
        id: check_approvals_status
        uses: ./.github/actions/check-approvals
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests for modified Apex components
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' }}
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false
          TEST_LEVEL: RunSpecifiedTests
          WAIT: 30
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_TEST }}
