name: Deploy To Test

on:
  pull_request_review:
    branches:
      - test
    paths:
      - 'force-app/**'
    types:
      - submitted

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    outputs:
      all_approved: ${{ steps.check.outputs.all_approved }}
    steps:
      - name: Check approvals
        id: check_approvals
        run: |
          const pr = context.payload.pull_request;

          const reviewsResponse = await github.rest.pulls.listReviews({
            owner: pr.base.user.login,
            repo: pr.base.repo.name,
            pull_number: pr.number
          });

          const requiredApprovers = pr.requested_reviewers.map(reviewer => reviewer.login);
          const approvedReviewers = reviewsResponse.data.filter(review => review.state === 'APPROVED').map(review => review.user.login);

          const checkApprovals = requiredApprovers.every(reviewer => approvedReviewers.includes(reviewer));

          console.log(`Required Approvers: ${requiredApprovers}`);
          console.log(`Approved Reviewers: ${approvedReviewers}`);
          console.log(`All required approvers approved: ${checkApprovals}`);

          return checkApprovals; // Returns true if all required approvers have approved
  deploy:
    needs: check_approvals
    if: needs.check_approvals.outputs.all_approved == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run tests for modified Apex components
      - name: Run tests for modified Apex components
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false  # or false, depending on your needs
          TEST_LEVEL: RunSpecifiedTests
          WAIT: 30
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_TEST }}