name: Deploy

on:
  pull_request_review:
    types:
      - submitted

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Approvals and Workflow Status
        id: check_approvals_status
        uses: ./.github/actions/check-approvals
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "dev" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_DEV }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=DELTA" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "test" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_TEST }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=FULL" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "main" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=QUICK" >> $GITHUB_ENV
          fi

      - name: Deploy changes to target branch (delta)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'DELTA' }}
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}

      - name: Deploy changes to target branch (full)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'FULL' }}
        uses: ./.github/actions/sf-deploy-full
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}

      - name: Deploy changes to target branch (quick)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'QUICK' }}
        uses: ./.github/actions/sf-deploy-quick
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}
