name: Deploy

on:
  pull_request_review:
    types:
      - submitted

run-name: >-
  ${{ github.event.pull_request.base.ref == 'int' && format('Deploy to INT by {0} PR Name: {1}', github.actor, github.event.pull_request.title) || 
      github.event.pull_request.base.ref == 'uat' && format('Deploy to UAT by {0} PR Name: {1}', github.actor, github.event.pull_request.title) ||
      github.event.pull_request.base.ref == 'main' && format('Deploy to PROD by {0} PR Name: {1}', github.actor, github.event.pull_request.title)
      }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Approvals and Workflow Status
        id: check_approvals_status
        uses: ./.github/actions/check-approvals
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "${{ vars.INT_BRANCH }}" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_INT }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=DELTA" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "${{ vars.UAT_BRANCH }}" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_UAT }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=FULL" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "${{ vars.MAIN_BRANCH }}" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_PROD }}" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=QUICK" >> $GITHUB_ENV
          fi

      - name: Deploy to target org (DELTA)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'DELTA' }}
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}
          DEPLOY_TYPE: ${{ env.DEPLOY_TYPE }}

      - name: Deploy to target org (FULL)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'FULL' }}
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          DEPLOY_TYPE: FULL
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}

      - name: Deploy to target org (QUICK)
        if: ${{ steps.check_approvals_status.outputs.check_approvals_status == 'success' && env.DEPLOY_TYPE == 'QUICK' }}
        uses: ./.github/actions/sf-deploy-quick
        with:
          DRY_RUN: false
          TEST_LEVEL: NoTestRun
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}
