name: Scheduled Full Deploy To Dev

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ vars.DEV_BRANCH }}
          fetch-depth: 0

      - name: Deploy full repository to ${{ vars.INT_ORG }} org
        uses: ./.github/actions/sf-deploy-full
        with:
          DRY_RUN: false
          TEST_LEVEL: RunLocalTests
          WAIT: 30
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_DEV }}