name: Full Deploy To Test

on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test
          fetch-depth: 0

      # Run tests for modified Apex components
      - name: Run tests for modified Apex components
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false  # or false, depending on your needs
          TEST_LEVEL: RunLocalTests
          WAIT: 30
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_TEST }}