name: "Merge"

on:
  workflow_run:
    workflows: 
      - Deploy To Test
    types:
      - completed

jobs:
  merge:
    runs-on: "ubuntu-latest"
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Print event context"
        run: |
          echo "Event context: ${{ toJson(github) }}"

      - name: "Set up GitHub Script"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.SFDX_WORKFLOW_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];
            const repository = context.repo;

            await github.rest.pulls.merge({
              owner: repository.owner,
              repo: repository.repo,
              pull_number: pullRequest.number,
              merge_method: "merge",
            });
