name: "Merge"

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

run-name: >-
  ${{ github.event.client_payload.base_ref == 'dev' && format('Merge to {0} by {1} PR Name: {2}', github.event.client_payload.base_ref, github.event.client_payload.user_login, github.event.client_payload.pr_title) || 
      github.event.client_payload.base_ref == 'test' && format('Merge to {0} by {1} PR Name: {2}', github.event.client_payload.base_ref, github.event.client_payload.user_login, github.event.client_payload.pr_title) ||
      github.event.client_payload.base_ref == 'main' && format('Merge to {0} by {1} PR Name: {2}', github.event.client_payload.base_ref, github.event.client_payload.user_login, github.event.client_payload.pr_title)
      }}

jobs:
  merge:
    runs-on: "ubuntu-latest"
    if: >
      github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: |
          echo "$GITHUB_CONTEXT"
      - name: "Auto Merge Pull Request"
        uses: ./.github/actions/merge
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"