name: "Merge"

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

run-name: >-
  ${{ github.event.pull_request.base.ref == 'dev' && format('Deploy to INT by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title) || 
      github.event.pull_request.base.ref == 'test' && format('Deploy to UAT by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title) ||
      github.event.pull_request.base.ref == 'main' && format('Deploy to PROD by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title)
      }}

jobs:
  merge:
    runs-on: "ubuntu-latest"
    if: >
      github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Auto Merge Pull Request"
        uses: ./.github/actions/merge
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"