name: "Merge"

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

permissions: write-all

run-name: >-
  ${{ github.event.workflow_run.pull_requests[0].base.ref == 'dev' && format('Merge to dev by {0} PR Name: {1}', github.actor, github.event.workflow_run.head_commit.message) || 
      github.event.workflow_run.pull_requests[0].base.ref == 'test' && format('Merge to test by {0} PR Name: {1}', github.actor, github.event.workflow_run.head_commit.message) ||
      github.event.workflow_run.pull_requests[0].base.ref == 'main' && format('Merge to main by {0} PR Name: {1}', github.actor, github.event.workflow_run.head_commit.message)
      }}

jobs:
  merge:
    runs-on: "ubuntu-latest"
    if: >
      github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        - name: Print event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: |
      - name: "Auto Merge Pull Request"
        uses: ./.github/actions/merge
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"