name: "Merge"

on:
  workflow_run:
    workflows: ["Validate Test Pull Request"]
    types:
      - "completed"

jobs:
  merge:
    runs-on: "ubuntu-latest"
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Set up GitHub Script"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];
            const repository = context.repo;

            await github.rest.pulls.merge({
              owner: repository.owner,
              repo: repository.repo,
              pull_number: pullRequest.number,
              merge_method: "merge",
            });
