name: Validate

on:
  pull_request:
    branches:
      - dev
      - test
      - prod
    paths:
      - 'force-app/**'

run-name: >-
  ${{ github.event.pull_request.base.ref == '$DEV_BRANCH' && format('Validate to $INT_ORG by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title) || 
      github.event.pull_request.base.ref == '$TEST_BRANCH' && format('Validate to $UAT_ORG by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title) ||
      github.event.pull_request.base.ref == '$PROD_BRANCH' && format('Validate to $PROD_ORG by {0} PR Name: {1}', github.event.pull_request.user.login, github.event.pull_request.title)
      }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SFDX Auth URL and Test Level
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "$DEV_BRANCH" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_DEV }}" >> $GITHUB_ENV
            echo "TEST_LEVEL=RunSpecifiedTests" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=DELTA" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "$TEST_BRANCH" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL_TEST }}" >> $GITHUB_ENV
            echo "TEST_LEVEL=RunLocalTests" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=FULL" >> $GITHUB_ENV
          elif [ "${{ github.event.pull_request.base.ref }}" == "$PROD_BRANCH" ]; then
            echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL }}" >> $GITHUB_ENV
            echo "TEST_LEVEL=RunLocalTests" >> $GITHUB_ENV
            echo "DEPLOY_TYPE=FULL" >> $GITHUB_ENV
          fi

      - name: Validate
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: true
          TEST_LEVEL: ${{ env.TEST_LEVEL }}
          WAIT: 30
          SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}
          DEPLOY_TYPE: ${{ env.DEPLOY_TYPE }}
